package GenerateSQL::Sql;
use v5.40;

sub generate($self, $json) {


}

1;



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

GenerateSQL::Sql


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<v5.40> 


=head1 METHODS

=head2 generate($self,

 generate($self,();


=cut

