use v5.40;
use feature 'class';
no warnings 'experimental::class';

our $VERSION = '0.01';

class Daje::Generate::Perl::PerlManager :isa(Daje::Generate::Perl::Base::Common)  {
    use Daje::Generate::Perl::Generate::Fields;
    use Daje::Generate::Perl::Generate::Methods;
    use Daje::Generate::Perl::Generate::Class;

    field $success :reader = 1;
    field $config :param :reader;

    method generate_classes() {
        my $length = scalar @{$self->json->{tables}};
        for (my $i = 0; $i < $length; $i++) {
            $self->_generate_table_class(@{$self->json->{tables}}[$i]);
        }
        $length = scalar $self->json->{views};
        for (my $i = 0; $i < $length; $i++) {
            $self->_generate_view_class(@{$self->json->{views}}[$i]);
        }
    }

    method _generate_table_class($table) {
        my $fields = $self->_get_fields($table);
        my $methods = $self->_methods($fields, $table);
        my $class = $self->_class($methods, $table);
        $self->_save_class($class, $table);
    }

    method _class($methods, $table) {
        my $template = $self->template();
        my $class = Daje::Generate::Perl::Generate::Class->new(
            json     => $table->{table},
            methods  => $methods,
            template => $template,
            config   => $config,
        );
        $class->generate();

        return $class;
    }

    method _methods($fields, $table) {
        my $template = $self->template();
        my $methods = Daje::Generate::Perl::Generate::Methods->new(
            json     => $table->{table},
            fields   => $fields,
            template => $template
        );
        $methods->generate();

        return $methods;
    }

    method _generate_view_class($view) {
        $view = $view;
    }

    method _get_fields($json) {
        my $template = $self->template();
        my $fields = Daje::Generate::Perl::Generate::Fields->new(
            json     => $json->{table},
            template => $template
        );
        $fields->generate();
        return $fields;
    }
}


1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

lib::Daje::Generate::Perl::PerlManager - lib::Daje::Generate::Perl::PerlManager


=head1 REQUIRES

L<feature> 

L<v5.40> 


=head1 METHODS


=cut

