use v5.40;
use feature 'class';
no warnings 'experimental::class';

class GenerateSQL::Sql::Table::Index :isa(GenerateSQL::Sql::Base::Common){

}
1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

lib::GenerateSQL::Sql::Table::Index - lib::GenerateSQL::Sql::Table::Index


=head1 REQUIRES

L<feature> 

L<v5.40> 


=head1 METHODS


=cut

