use v5.40;
use feature 'class';
no warnings 'experimental::class';

our $VERSION = '0.02';

class GenerateSQL {

    field $source_path :param;
    field $target_path :param;

    sub process () {

    }
}



1;




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

lib::Generate - lib::Generate


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<feature> 

L<v5.40> 


=head1 METHODS

=head2 process

 process();


=cut

