use v5.40;
use feature 'class';
no warnings 'experimental::class';

our $VERSION = '0.01';

class Daje::GeneratePerl :isa(Daje::Generate::Base::Common) {
    use Mojo::JSON qw{from_json};
    use Mojo::File;
    use Daje::Generate::Perl::PerlManager;

    method process() {
        $self->_load_config();
        my $json = $self->get_json();
        $self->create_perl($json);

    }

    method create_perl($json) {
        my $manager = Daje::Generate::Perl::PerlManager->new(
            config_path => $config_path
        );


    }

    method get_json() {
        my $path = $self->config->{DATABASE}->{schema_dir};
        my $json_txt = Mojo::File->new($path . "schema.json")->slurp();
        my $json = from_json($json_txt);

        return $json;
    }
}


1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

lib::Daje::GeneratePerl - lib::Daje::GeneratePerl


=head1 REQUIRES

L<Daje::Generate::Perl::PerlManager> 

L<feature> 

L<v5.40> 


=head1 METHODS


=cut

