use v5.40;
use feature 'class';
no warnings 'experimental::class';

our $VERSION = '0.08';

class  Daje::Generate :isa(Daje::Generate::Base::Common) {
    use Daje::GenerateSQL;
    use Daje::GenerateSchema;
    use Daje::GeneratePerl;

    method process () {
        Daje::GenerateSQL->new(
            config_path => $self->config_path(),
        )->process();
        Daje::GenerateSchema->new(
            config_path => $self->config_path(),
        )->process();
        Daje::GeneratePerl->new(
            config_path => $self->config_path(),
        )->process();
    }
}

1;









#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Generate


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<Mojo::Base> 

L<v5.40> 


=head1 METHODS

=head2 process

 process();


=cut

