package Daje::Generate::Templates::Perl;
use v5.40;

1;

__DATA__

@@ class
use v5.40;
use feature 'class';
no warnings 'experimental::class';

# Autogenerated class <<date>>
# Any manual changes to this class will be overwritten next time its generated

class <<name_space>><<classname>> :isa(<<base_name_space>><<base_class_name>>) {

    <<fields>>

    <<methods>>


};

@@ method

    method <<method_name>> ($self, <<parameters>>) {
        <<method_content>>
    };


@@ baseclass
use v5.40;
use feature 'class';
no warnings 'experimental::class';

# Autogenerated class <<date>>
# Any manual changes to this class will be overwritten next time its generated

class <<base_name_space>> {
    field $db :param :reader;


};

@@ interface
use v5.40;
use feature 'class';
no warnings 'experimental::class';

# Autogenerated class <<date>>
# This class is generated once. Any over rides or special methods should be put here

class <<interface>><<classname>> :isa(<<name_space>><<classname>>) {


};

@@ load_from_pkey

method load_pkey($<<primary_key>>) {
    my $result = $self->db->select(
        '<<table_name>>',
            [<<select_fields>>],
            {<<primary_key>> => $<<primary_key>>}
    );

    my $hash;
    $hash = $result->hash if $result and $result->rows > 0;
    return $hash;
}

@@ load_from_fkey

method load_<<foreign_key>>($<<foreign_key>> ) {
    my $result = $db->select(
        '<<table_name>>',
            [<<select_fields>>],
        {<<foreign_key>> => $<<foreign_key>>}
    );

    my $hashes;
    $hashes = $result->hashes if $result and $result->rows > 0;
    return $hashes;
}

method load_list($key_value) {
    my $result = $db->select(
        '<<table_name>>',
            [<<select_fields>>],
        {$key_value}
    );

    my $hashes;
    $hashes = $result->hashes if $result and $result->rows > 0;
    return $hashes;
}
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Generate::Templates::Perl


=head1 DESCRIPTION

Autogenerated class <<date>>
Any manual changes to this class will be overwritten next time its generated


=head1 REQUIRES

L<feature> 

L<v5.40> 

L<feature> 

L<v5.40> 

L<v5.40> 


=head1 METHODS


=cut

